// <auto-generated />
using System;
using LootNet_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LootNet_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429212918_UpdateII")]
    partial class UpdateII
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BodyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BootsId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GlovesId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LegsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeaponSlot1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeaponSlot2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeaponSlot3Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeaponSlot4Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.Battle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("Battle");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.BattleEnemy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BattleId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDisorganized")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LeftHandItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RightHandItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SkipNextTurn")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BattleId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("BattleEnemy");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.EnemyGeneration.ScenarioSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StageScenarioId")
                        .HasColumnType("uuid");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("StageScenarioId");

                    b.ToTable("ScenarioSlot");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.EnemyGeneration.StageProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Falloff")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StageIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("StageProfiles");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.EnemyGeneration.StageScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("EnemyCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("StageProfileId")
                        .HasColumnType("uuid");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("StageProfileId");

                    b.ToTable("StageScenario");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BattleIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPlayerDisorganized")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LeftHandItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("PlayerCurrentHp")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerMaxHp")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("integer");

                    b.Property<bool>("PlayerSkipNextTurn")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RightHandItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Armor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmorType")
                        .HasColumnType("integer");

                    b.Property<double>("BluntResistance")
                        .HasColumnType("double precision");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<double>("CutResistance")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.DistributionSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemElementSettingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemParameterSettingId")
                        .HasColumnType("uuid");

                    b.Property<double>("Max")
                        .HasColumnType("double precision");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ItemElementSettingId");

                    b.HasIndex("ItemParameterSettingId");

                    b.ToTable("DistributionSegments", t =>
                        {
                            t.HasCheckConstraint("CK_DistributionSegment_OnlyOneParent", "(\"ItemParameterSettingId\" IS NULL AND \"ItemElementSettingId\" IS NOT NULL)\r\n                  OR\r\n                  (\"ItemParameterSettingId\" IS NOT NULL AND \"ItemElementSettingId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.GenerationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GenerationProfiles");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemElementSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ElementType")
                        .HasColumnType("integer");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("ItemElementSettings");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemGenerationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ArmorType")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WeaponType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ItemGenerationRules");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemParameterSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Parameter")
                        .HasColumnType("integer");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("ItemParameterSettings");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemTypeWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ArmorType")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WeaponType")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ItemTypeWeights");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArmorId")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemElementType")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeaponId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArmorId");

                    b.HasIndex("WeaponId");

                    b.ToTable("ItemElements", t =>
                        {
                            t.HasCheckConstraint("CK_ItemElement_OnlyOneOwner", "(\"WeaponId\" IS NULL AND \"ArmorId\" IS NOT NULL)\r\n                  OR\r\n                  (\"WeaponId\" IS NOT NULL AND \"ArmorId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("LootNet_API.Models.Items.MarketInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId");

                    b.ToTable("MarketInventoryItems");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.RunInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ItemId");

                    b.ToTable("RunInventoryItems");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Blunt")
                        .HasColumnType("double precision");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<double>("Cut")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeaponType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("LootNet_API.Models.Logs.AdminLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("LootNet_API.Models.Market.MarketListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSold")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Price");

                    b.ToTable("MarketListings");
                });

            modelBuilder.Entity("LootNet_API.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LootNet_API.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("LootNet_API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlockReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BlockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Currency")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDailyReward")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Equipment", b =>
                {
                    b.HasOne("LootNet_API.Models.User", null)
                        .WithOne("Equipment")
                        .HasForeignKey("Equipment", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.Battle", b =>
                {
                    b.HasOne("LootNet_API.Models.GameRun.Run", null)
                        .WithMany("Battles")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.BattleEnemy", b =>
                {
                    b.HasOne("LootNet_API.Models.GameRun.Battle", null)
                        .WithMany("Enemies")
                        .HasForeignKey("BattleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.EnemyGeneration.ScenarioSlot", b =>
                {
                    b.HasOne("LootNet_API.Models.GameRun.EnemyGeneration.StageScenario", null)
                        .WithMany("Slots")
                        .HasForeignKey("StageScenarioId");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.EnemyGeneration.StageScenario", b =>
                {
                    b.HasOne("LootNet_API.Models.GameRun.EnemyGeneration.StageProfile", null)
                        .WithMany("Scenarios")
                        .HasForeignKey("StageProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.DistributionSegment", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.Generation.ItemElementSetting", null)
                        .WithMany("Segments")
                        .HasForeignKey("ItemElementSettingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LootNet_API.Models.Items.Generation.ItemParameterSetting", null)
                        .WithMany("Segments")
                        .HasForeignKey("ItemParameterSettingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemElementSetting", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.Generation.ItemGenerationRule", null)
                        .WithMany("Elements")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemGenerationRule", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.Generation.GenerationProfile", null)
                        .WithMany("Rules")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemParameterSetting", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.Generation.ItemGenerationRule", null)
                        .WithMany("Parameters")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemTypeWeight", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.Generation.GenerationProfile", null)
                        .WithMany("TypeWeights")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootNet_API.Models.Items.InventoryItem", b =>
                {
                    b.HasOne("LootNet_API.Models.User", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemElement", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.Armor", null)
                        .WithMany("Elements")
                        .HasForeignKey("ArmorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LootNet_API.Models.Items.Weapon", null)
                        .WithMany("Elements")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LootNet_API.Models.Items.MarketInventoryItem", b =>
                {
                    b.HasOne("LootNet_API.Models.User", null)
                        .WithMany("MarketInventoryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootNet_API.Models.Items.RunInventoryItem", b =>
                {
                    b.HasOne("LootNet_API.Models.User", null)
                        .WithMany("RunInventoryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LootNet_API.Models.User", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.Generation.GenerationProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.Battle", b =>
                {
                    b.Navigation("Enemies");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.EnemyGeneration.StageProfile", b =>
                {
                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.EnemyGeneration.StageScenario", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("LootNet_API.Models.GameRun.Run", b =>
                {
                    b.Navigation("Battles");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Armor", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.GenerationProfile", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("TypeWeights");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemElementSetting", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemGenerationRule", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Generation.ItemParameterSetting", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Weapon", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("LootNet_API.Models.User", b =>
                {
                    b.Navigation("Equipment")
                        .IsRequired();

                    b.Navigation("InventoryItems");

                    b.Navigation("MarketInventoryItems");

                    b.Navigation("RunInventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
