// <auto-generated />
using System;
using LootNet_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LootNet_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402200048_UpdateII")]
    partial class UpdateII
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LootNet_API.Models.Items.Armor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmorType")
                        .HasColumnType("integer");

                    b.Property<double>("BluntResistance")
                        .HasColumnType("double precision");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<double>("CutResistance")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.DistributionSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemElementSettingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemParameterSettingId")
                        .HasColumnType("uuid");

                    b.Property<double>("Max")
                        .HasColumnType("double precision");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ItemElementSettingId");

                    b.HasIndex("ItemParameterSettingId");

                    b.ToTable("DistributionSegment");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.GenerationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GenerationProfiles");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArmorId")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemElementType")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeaponId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArmorId");

                    b.HasIndex("WeaponId");

                    b.ToTable("ItemElement");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemElementSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ElementType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ItemGenerationRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemGenerationRuleId");

                    b.ToTable("ItemElementSetting");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemGenerationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ArmorType")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GenerationProfileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WeaponType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenerationProfileId");

                    b.ToTable("ItemGenerationRules");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemParameterSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ItemGenerationRuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Parameter")
                        .HasColumnType("integer");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemGenerationRuleId");

                    b.ToTable("ItemParameterSetting");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemTypeWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ArmorType")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GenerationProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WeaponType")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GenerationProfileId");

                    b.ToTable("ItemTypeWeight");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Blunt")
                        .HasColumnType("double precision");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<double>("Cut")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeaponType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("LootNet_API.Models.MarketListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MarketListings");
                });

            modelBuilder.Entity("LootNet_API.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("LootNet_API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastDailyReward")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.DistributionSegment", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.ItemElementSetting", null)
                        .WithMany("Segments")
                        .HasForeignKey("ItemElementSettingId");

                    b.HasOne("LootNet_API.Models.Items.ItemParameterSetting", null)
                        .WithMany("Segments")
                        .HasForeignKey("ItemParameterSettingId");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemElement", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.Armor", null)
                        .WithMany("Elements")
                        .HasForeignKey("ArmorId");

                    b.HasOne("LootNet_API.Models.Items.Weapon", null)
                        .WithMany("Elements")
                        .HasForeignKey("WeaponId");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemElementSetting", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.ItemGenerationRule", null)
                        .WithMany("Elements")
                        .HasForeignKey("ItemGenerationRuleId");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemGenerationRule", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.GenerationProfile", null)
                        .WithMany("Rules")
                        .HasForeignKey("GenerationProfileId");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemParameterSetting", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.ItemGenerationRule", null)
                        .WithMany("Parameters")
                        .HasForeignKey("ItemGenerationRuleId");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemTypeWeight", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.GenerationProfile", null)
                        .WithMany("TypeWeights")
                        .HasForeignKey("GenerationProfileId");
                });

            modelBuilder.Entity("LootNet_API.Models.User", b =>
                {
                    b.HasOne("LootNet_API.Models.Items.GenerationProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Armor", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.GenerationProfile", b =>
                {
                    b.Navigation("Rules");

                    b.Navigation("TypeWeights");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemElementSetting", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemGenerationRule", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.ItemParameterSetting", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("LootNet_API.Models.Items.Weapon", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
